from turtle import *
def tégla(a, b, szín):
    color("brown", szín)
    begin_fill()
    for i in range(2):
        fd(a)
        lt(90)
        fd(b)
        lt(90)
    end_fill()
def hálószoba():
    speed(0)
    ht()
    rt(180)
    pensize(10)
    pencolor("grey")
    fd(50)
    pensize(5)
    pencolor("blue")
    for i in range(3):
        fd(30)
        dot(8)
    pensize(10)
    pencolor("grey")
    fd(50)
    lt(90)
    fd(300)
    lt(90)
    fd(190)
    lt(90)
    pensize(5)
    pencolor("brown")
    fd(60)
    pensize(10)
    pencolor("grey")
    fd(240)
    lt(90)
    up()
    fd(5)
    lt(90)
    fd(5)
    rt(90)
    down()
    pensize(1)
    tégla(45, 45, "brown")
    fd(45)
    tégla(90, 150, "lime")
    fd(90)
    tégla(45, 45, "brown")
    up()
    fd(45)
    lt(90)
    fd(140)
    down()
    tégla(100, 35, "brown")
hálószoba()
