from turtle import *
speed(0)
ht()
def irattartó(méret, darab):
    mode("logo")
    for i in range(darab):
        for j in range(2):
            fd(méret)
            rt(90)
            fd(méret/4)
            rt(90)
        up()
        fd(méret/4/2)
        rt(90)
        fd(méret/8)
        dot(méret/8)
        lt(90)
        fd(méret/4)
        rt(90)
        back(méret/16)
        down()
        pensize(méret/16/2)
        fd(méret/8)
        up()
        fd(méret/16)
        rt(90)
        fd(méret/4 + méret/8)
        lt(180)
        down()
        pensize(1)
irattartó(200, 4)
