from turtle import *
def egyik(mag, szél, táv):
    speed(0)
    ht()
    pensize(3)
    pencolor("brown")
    for i in range(2):
        for j in range(4):
            fd(táv)
            rt(90)
        fd(táv+szél)
        for j in range(4):
            fd(táv)
            rt(90)
        lt(90)
        fd(mag)
        lt(90)
        back(táv)
    pensize(1)
    pencolor("black")
def másik(mag, szél, táv):
    speed(0)
    ht()
    pensize(3)
    pencolor("brown")
    up()
    lt(90)
    fd(táv)
    down()
    for i in range(2):
       fd(mag - 2*táv)
       rt(90)
       fd(2*táv)
       lt(90)
       fd(2*táv)
       rt(90)
       fd(szél - 2*táv)
       rt(90)
       fd(2*táv)
       lt(90)
       fd(2*táv)
       rt(90)
    pensize(1)
    pencolor("black")
def ajtó(mag, szél, táv):
    speed(0)
    ht()
    for i in range(2):
        fd(szél)
        lt(90)
        fd(mag)
        lt(90)
    up()
    fd(2*táv)
    lt(90)
    fd(3*táv)
    rt(90)
    down()
    egyik(mag - 6*táv, szél - 6*táv, táv)
    másik(mag - 6*táv, szél - 6*táv, táv)
ajtó(200, 150, 10)
    
