from turtle import *
def csavaros(hossz):
    speed(0)
    ht()
    lt(45)
    color("orange", "brown")
    pensize(3)
    for i in range(4):
        begin_fill()
        fd(hossz)
        rt(90)
        fd(3*hossz/4)
        rt(90)
        fd(hossz/2)
        rt(90)
        fd(hossz/4)
        rt(90)
        for j in range(2):
            fd(hossz/4)
            lt(90)
        fd(3*hossz/4)
        rt(90)
        fd(hossz/4)
        end_fill()
        up()
        back(2*hossz/4)
        lt(90)
        fd(hossz/4)
        rt(90)
        down()
csavaros(50)
