from turtle import *
def háromszög(a):
    for i in range(3):
        fd(a)
        lt(120)
def egyik(h):
    speed(0)
    ht()
    háromszög(3*h)
    up()
    rt(150)
    back(h*3**0.5)    
    down()
    for i in range(3):
        fd(h*3**0.5)
        back(h*3**0.5)
        rt(120)
    up()
    fd(0.5*h*3**0.5)
    down()
    lt(150)
    háromszög(1.5*h)
    rt(60)
    up()
    fd(1.5*h)
    lt(120)
    down()
    háromszög(3*h)
def háromszög1(a):
    fd(a)
    rt(150)
    fd(a/3**0.5)
    rt(60)
    fd(a/3**0.5)
    rt(150)
def másik(h):
    speed(0)
    ht()
    for i in range(3):
        háromszög1(2*h)
        up()
        fd(2*h)
        lt(120)
        down()
    up()
    fd(h)
    rt(30)
    back(h/3**0.5)
    lt(30)
    down()
    for i in range(3):
        háromszög1(h)
        up()
        fd(h)
        lt(120)
        down()
másik(150)
