from turtle import *
mode("logo")
speed(0)
ht()
def tégla(h, szín):
    fillcolor(szín)
    begin_fill()
    fd(h)
    rt(90)
    fd(h/2)
    rt(90)
    fd(h/2)
    lt(90)
    fd(h/2)
    rt(90)
    fd(h/2)
    rt(90)
    fd(h)
    rt(90)
    end_fill()
def hármas(h, szín1, szín2, szín3):
    for i in [szín1, szín2, szín3]:
        tégla(h, i)
        up()
        fd(2*h)
        rt(90)
        down()
def téglalap(h):
    hármas(h, "red", "lime", "yellow")
    up()
    back(h)
    lt(90)
    back(2*h)
    down()
    hármas(h, "purple", "orange", "blue")
    up()
    rt(90)
    fd(h/2)
    lt(90)
    back(h/2)
    down()
    tégla(h, "brown")
    up()
    fd(2*h)
    rt(90)
    fd(h)
    rt(90)
    down()
    tégla(h, "green")
téglalap(100)
        
