from turtle import *
mode("logo")
speed(0)
ht()
def irattartó(méret, darab):
    for i in range(darab):
        for j in range(2):
            fd(méret)
            rt(90)
            fd(méret/4)
            rt(90)
        up()
        fd(méret/12 + méret/24)
        rt(90)
        fd(méret/12 + méret/24)
        dot(méret/12)
        lt(90)
        fd(3*méret/12 + méret/60)
        rt(90)
        down()
        pensize(méret/40)
        for k in range(3):
            fd(méret/5/4)
            back(méret/5/2)
            fd(méret/5/4)
            up()
            lt(90)
            fd(méret/40 + méret/30)
            rt(90)
            down()
        pensize(1)
        up()
        home()
        rt(90)
        fd((i+1)*méret/4)
        lt(90)
        down()
irattartó(200, 4)
