from turtle import *
def négyzet(hossz):
    speed(0)
    ht()
    for i in range(4):
        fd(hossz)
        lt(90)
def alap(hossz):
    négyzet(hossz)
    fd(hossz)
    lt(135)
    fd(hossz*2**0.5)
    rt(135)
    up()
    fd(hossz/6)
    rt(90)
    fd(hossz/6)
    down()
    négyzet(2*hossz/3)
    up()
    fd(hossz/6)
    lt(90)
    fd(hossz/6)
    rt(90)
    down()
    fillcolor("white")
    begin_fill()
    négyzet(hossz/3)
    end_fill()
    up()
    fd(4*hossz/6)
    rt(90)
    fd(2*hossz/6)
    rt(135)
    down()
    fd(hossz*2**0.5)
    back(hossz*2**0.5)
    rt(45)
def sor(db, hossz):
    for i in range(db):
        alap(hossz)
        fd(hossz)
    back(db*hossz)
def mozaik(sdb, db, hossz):
    for i in range(sdb):
        sor(db, hossz)
        lt(90)
        fd(hossz)
        rt(90)
mozaik(4, 2, 60)
