from turtle import *
def téglalap(a, b, szín):
    color(szín)
    begin_fill()
    for i in range(2):
        fd(a)
        lt(90)
        fd(b)
        lt(90)
    end_fill()
    color("black")
def hatter(h):
    téglalap(26*h, 10*h, "lime")
    lt(90)
    up()
    fd(10*h)
    down()
    rt(90)
    téglalap(26*h, 9*h, "light blue")
def hazsor(h, db):
    up()
    fd(h/2)
    down()
    for i in range(db):
        téglalap(h, h, "blue")
        up()
        lt(90)
        fd(h)
        rt(90)
        down()
        color("red1")
        begin_fill()
        for i in range(3):
            fd(h)
            lt(120)
        end_fill()
        up()
        fd(2*h)
        rt(90)
        fd(h)
        lt(90)
        down()
def fa(méret):
    pensize(méret)
    color("brown3")
    fd(4*méret)
    color("green")
    dot(4*méret)
    up()
    back(4*méret)
    down()
def golf(h):
    ht()
    speed(0)
    up()
    goto(-13*h, -9*h)
    down()
    hatter(h)
    hazsor(1.2*h, 5)
    up()
    lt(90)
    fd(6*h)
    color("yellow")
    dot(2*h)
    down()
    pensize(0.3*h)
    for i in range(10):
        up()
        fd(1.3*h)
        down()
        fd(1.4*h)
        up()
        back(2.7*h)
        down()
        rt(36)
    color("black")
    up()
    back(8*h)
    rt(90)
    fd(h)
    lt(90)
    down()
    fa(0.7*h)
    up()
    rt(90)
    fd(3*h)
    lt(90)
    fd(1.5*h)
    down()
    fa(0.5*h)
    up()
    rt(90)
    fd(3.5*h)
    lt(90)
    back(2*h)
    down()
    fa(h)
    up()
    rt(90)
    fd(3*h)
    lt(90)
    fd(2*h)
    down()
    fa(0.4*h)
    up()
    back(8*h)
    lt(90)
    fd(1.1*h)
    dot(2*h, "black")
    lyuk_x = xcor()
    lyuk_y = ycor()
    back(0.7*h)
    rt(90)
    fd(0.65*h)
    down()
    color("brown4")
    pensize(0.4*h)
    fd(9*h)
    pensize(0.3*h)
    color("red", "white")
    begin_fill()
    for i in range(3):
        fd(2.5*h)
        lt(120)
    end_fill()
    pensize(0.25*h)
    for i in [0.6*h, 1.2*h, 1.8*h]:
        for j in range(3):
            fd(i)
            lt(120)
    labda = Turtle()
    labda.ht()
    labda.shape("circle")
    labda.shapesize(0.07*h)
    labda.color("yellow")
    labda.up()
    labda.goto(-5*h, lyuk_y)
    labda.st()
    uto = Turtle()
    uto.ht()
    uto.shape("square")
    uto.shapesize(0.5*h, 0.04*h)
    uto.color("purple")
    uto.up()
    uto.goto(-6.2*h, lyuk_y + 4.5*h)
    uto.st()
    for i in range(45):
        uto.rt(1)
    for i in range(45):
        uto.lt(1)
    while labda.xcor() < lyuk_x:
        labda.fd(0.1*h)
    for i in range(20):
        labda.shapesize(0.07*h/(i+1))
    labda.ht()
golf(30)
